In [3]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(pd.read_csv("dataset.csv"))

In [11]:
df.sample(10)

,profile_age_days,applications_7d,applications_30d,avg_applications_30d,app_to_avg_ratio,skills_count,endorsements_count,experience_years,skills_to_exp_ratio,institution_risk_score,...,is_new_device,ip_risk_score,email_risk_score,login_velocity_24h,failed_logins_24h,copy_paste_ratio,feature_noise_1,feature_noise_2,feature_noise_3,feature_noise_4
5237,73,5,7,9.7074,0.0240,21,47,7.2,2.640,0.0884,...,0,0.1060,0.2051,1,0,0.2289,1.1504,0.9113,7,0.8920
9259,1980,5,15,7.3633,0.0676,38,51,12.5,2.829,0.0901,...,1,0.2095,0.5793,1,1,0.1011,1.0526,0.4797,84,0.1952
701,1763,2,3,1.2268,0.0794,5,46,0.8,3.140,0.3714,...,0,0.4675,0.5062,0,0,0.1444,-1.9307,1.0813,6,0.9449
9531,110,2,12,1.0747,0.3610,5,39,1.7,2.007,0.2435,...,0,0.1837,0.3926,3,0,0.3752,0.7531,1.6399,74,0.1680
2681,2414,1,12,3.0890,0.1281,19,2,7.9,2.141,0.0443,...,0,0.1813,0.0908,0,0,0.0864,0.2893,-1.5498,54,0.6961
1595,2098,3,19,4.1875,0.1500,35,31,11.7,2.828,0.4808,...,1,0.3033,0.1908,1,0,0.2956,0.1567,1.1951,57,0.2661
18,703,1,6,7.6741,0.0259,12,28,2.8,3.341,0.0583,...,0,0.2172,0.0890,2,0,0.2892,0.3252,-0.7492,35,0.7398
9966,175,2,3,5.2513,0.0189,29,2,10.7,2.533,0.3824,...,0,0.1529,0.3237,1,0,0.1114,-0.4632,-0.7729,11,0.9615
9786,2831,5,19,7.5379,0.0837,10,57,4.7,1.906,0.0612,...,0,0.3738,0.1851,3,0,0.4854,1.9575,0.6502,53,0.7952
1739,682,1,7,5.4749,0.0424,24,8,8.3,2.643,0.0722,...,0,0.2361,0.2130,1,1,0.1389,-0.5124,1.2044,41,0.5058

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   profile_age_days         10000 non-null  int64
 1   applications_7d          10000 non-null  int64
 2   applications_30d         10000 non-null  int64
 3   avg_applications_30d     10000 non-null  float64
 4   app_to_avg_ratio         10000 non-null  float64
 5   skills_count             10000 non-null  int64
 6   endorsements_count       10000 non-null  int64
 7   experience_years         10000 non-null  float64
 8   skills_to_exp_ratio      10000 non-null  float64
 9   institution_risk_score   10000 non-null  float64
 10  company_risk_score       10000 non-null  float64
 11  gpa_anomaly_score        10000 non-null  float64
 12  tenure_gap_months        10000 non-null  float64
 13  avg_tenure_months        10000 non-null  float64
 14  time_since_last_app_hrs  10000 non-null  float64
 15  is_new_device            10000 non-null  int64
 16  ip_risk_score            10000 non-null  float64
 17  email_risk_score         10000 non-null  float64
 18  login_velocity_24h       10000 non-null  int64
 19  failed_logins_24h        10000 non-null  int64
 20  copy_paste_ratio         10000 non-null  float64
 21  feature_noise_1          10000 non-null  float64
 22  feature_noise_2          10000 non-null  float64
 23  feature_noise_3          10000 non-null  int64
 24  feature_noise_4          10000 non-null  float64
dtypes: float64(16), int64(9)
memory usage: 1.9 MB

In [9]:
df.describe()

,profile_age_days,applications_7d,applications_30d,avg_applications_30d,app_to_avg_ratio,skills_count,endorsements_count,experience_years,skills_to_exp_ratio,institution_risk_score,...,is_new_device,ip_risk_score,email_risk_score,login_velocity_24h,failed_logins_24h,copy_paste_ratio,feature_noise_1,feature_noise_2,feature_noise_3,feature_noise_4
count,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,1820.4377,4.627900,16.203900,4.511767,0.225676,23.747700,29.37900,8.974550,2.978060,0.238988,...,0.154800,0.229261,0.237738,1.797100,0.337500,0.255331,-0.005507,0.000351,49.672300,0.501309
std,1053.3482,11.110787,30.977493,4.081290,0.672068,17.863084,17.31971,8.353894,4.043673,0.165487,...,0.361732,0.151808,0.162732,3.058769,0.665911,0.151350,1.000489,0.996966,28.654808,0.288530
min,1.0000,0.000000,0.000000,0.100000,0.000000,1.000000,0.00000,0.200000,0.651000,0.000700,...,0.000000,0.000400,0.000100,0.000000,0.000000,0.000700,-3.664300,-3.750700,0.000000,0.000100
25%,912.0000,1.000000,8.000000,1.928825,0.058800,11.000000,14.00000,3.400000,2.091000,0.112175,...,0.000000,0.109900,0.113075,1.000000,0.000000,0.139475,-0.669125,-0.672850,25.000000,0.254275
50%,1812.5000,4.000000,13.000000,3.284400,0.118400,18.000000,30.00000,6.200000,2.547500,0.206000,...,0.000000,0.202200,0.205950,1.000000,0.000000,0.232400,-0.007000,0.015850,50.000000,0.496550
75%,2728.0000,6.000000,18.000000,5.586375,0.229450,30.000000,44.00000,11.400000,3.051000,0.331000,...,0.000000,0.320225,0.330100,2.000000,1.000000,0.345425,0.660375,0.663250,74.000000,0.755900
max,3649.0000,149.000000,448.000000,30.000000,29.966800,80.000000,59.00000,40.000000,80.000000,0.985100,...,1.000000,0.861900,0.990900,39.000000,5.000000,0.961500,4.093200,4.144200,99.000000,1.000000

In [12]:
df.corr()

,profile_age_days,applications_7d,applications_30d,avg_applications_30d,app_to_avg_ratio,skills_count,endorsements_count,experience_years,skills_to_exp_ratio,institution_risk_score,...,is_new_device,ip_risk_score,email_risk_score,login_velocity_24h,failed_logins_24h,copy_paste_ratio,feature_noise_1,feature_noise_2,feature_noise_3,feature_noise_4
profile_age_days,1.000000,-0.009963,-0.010952,0.024088,-0.000629,0.004396,-0.004563,0.000321,-0.145008,0.005835,...,-0.003860,0.003539,0.019045,0.000943,-0.002786,-0.044745,0.016400,-0.009458,0.017404,0.011321
applications_7d,-0.009963,1.000000,0.882977,-0.017007,0.613309,-0.004919,0.000661,-0.009175,-0.002589,-0.016284,...,-0.000049,0.001358,0.010173,-0.004711,-0.013911,0.012205,0.001560,0.010229,-0.009505,0.000669
applications_30d,-0.010952,0.882977,1.000000,-0.013925,0.703240,-0.003920,0.001770,-0.008452,-0.003465,-0.008359,...,0.003306,-0.004575,0.005926,-0.003724,-0.009717,0.018156,0.012451,0.004949,-0.006545,-0.003603
avg_applications_30d,0.024088,-0.017007,-0.013925,1.000000,-0.177053,0.008945,-0.002259,0.002217,-0.007420,-0.002230,...,-0.016253,-0.004809,-0.007278,-0.013007,0.003687,-0.013293,0.007977,-0.004281,-0.007114,0.006085
app_to_avg_ratio,-0.000629,0.613309,0.703240,-0.177053,1.000000,-0.005257,-0.003503,-0.005997,-0.004883,0.007315,...,0.006788,0.001104,0.015999,-0.007556,0.007295,0.007554,0.005980,0.002677,0.020676,-0.014923
skills_count,0.004396,-0.004919,-0.003920,0.008945,-0.005257,1.000000,-0.009003,0.951142,-0.027076,-0.019416,...,0.006912,0.014570,-0.000740,-0.010545,-0.012447,-0.011988,-0.005491,0.006643,-0.014723,0.024674
endorsements_count,-0.004563,0.000661,0.001770,-0.002259,-0.003503,-0.009003,1.000000,-0.013777,-0.008888,-0.000191,...,-0.012398,0.015031,0.002436,0.002571,-0.007320,-0.003985,0.011297,0.002188,-0.006895,-0.014247
experience_years,0.000321,-0.009175,-0.008452,0.002217,-0.005997,0.951142,-0.013777,1.000000,-0.070038,-0.022039,...,0.002214,0.015528,-0.001264,-0.013190,-0.009590,-0.014589,-0.001185,0.011254,-0.011570,0.022639
skills_to_exp_ratio,-0.145008,-0.002589,-0.003465,-0.007420,-0.004883,-0.027076,-0.008888,-0.070038,1.000000,-0.006194,...,0.008765,-0.016011,-0.002772,-0.007224,-0.012463,0.269463,-0.015262,0.003920,-0.005668,0.008154
institution_risk_score,0.005835,-0.016284,-0.008359,-0.002230,0.007315,-0.019416,-0.000191,-0.022039,-0.006194,1.000000,...,0.005437,-0.000708,0.011929,-0.000007,0.005626,-0.001708,0.005606,-0.001240,0.005497,-0.014561
company_risk_score,0.008226,-0.010460,-0.009321,0.005534,0.002082,0.005365,0.008658,0.003203,0.012830,0.115693,...,-0.018054,0.007728,0.016169,-0.009029,0.003835,-0.017964,0.012741,-0.003227,-0.008990,-0.004161
gpa_anomaly_score,0.009160,-0.011005,-0.009751,-0.004214,0.002785,-0.008355,0.008132,-0.006076,-0.020826,0.156097,...,-0.012029,-0.003244,-0.001201,0.000636,-0.009131,-0.006007,0.004401,0.006958,0.003997,0.000026
tenure_gap_months,0.021428,-0.009350,-0.006185,-0.014516,-0.009687,-0.004211,0.020700,-0.004034,-0.019629,0.159884,...,-0.007047,-0.004566,0.005210,0.009028,0.001913,-0.018765,0.001547,0.002614,0.004729,-0.005002
avg_tenure_months,0.007429,0.012216,0.004931,-0.006875,0.013588,-0.004600,0.001574,-0.006480,0.010817,0.005739,...,-0.011576,-0.006656,0.001137,-0.008272,-0.022910,0.014313,0.005208,0.009740,0.000678,0.005346
time_since_last_app_hrs,-0.004064,-0.061814,-0.062483,-0.009051,-0.040826,-0.008464,-0.004278,-0.007371,-0.000449,0.011902,...,-0.006658,0.032722,0.005740,0.015726,0.008773,-0.002554,-0.023806,0.006369,0.003842,0.008384
is_new_device,-0.003860,-0.000049,0.003306,-0.016253,0.006788,0.006912,-0.012398,0.002214,0.008765,0.005437,...,1.000000,0.009032,0.092174,0.216306,0.130596,0.003895,0.026359,0.014793,0.008918,0.010143
ip_risk_score,0.003539,0.001358,-0.004575,-0.004809,0.001104,0.014570,0.015031,0.015528,-0.016011,-0.000708,...,0.009032,1.000000,0.016150,0.014877,0.012759,0.004452,-0.011492,-0.006047,0.001063,-0.003969
email_risk_score,0.019045,0.010173,0.005926,-0.007278,0.015999,-0.000740,0.002436,-0.001264,-0.002772,0.011929,...,0.092174,0.016150,1.000000,0.289524,0.156750,0.005842,0.000642,-0.012593,-0.028287,-0.007067
login_velocity_24h,0.000943,-0.004711,-0.003724,-0.013007,-0.007556,-0.010545,0.002571,-0.013190,-0.007224,-0.000007,...,0.216306,0.014877,0.289524,1.000000,0.438451,-0.003732,0.002962,0.009060,0.002392,0.000584
failed_logins_24h,-0.002786,-0.013911,-0.009717,0.003687,0.007295,-0.012447,-0.007320,-0.009590,-0.012463,0.005626,...,0.130596,0.012759,0.156750,0.438451,1.000000,-0.015735,0.002555,0.004097,0.004518,-0.002108
copy_paste_ratio,-0.044745,0.012205,0.018156,-0.013293,0.007554,-0.011988,-0.003985,-0.014589,0.269463,-0.001708,...,0.003895,0.004452,0.005842,-0.003732,-0.015735,1.000000,0.000747,0.015760,-0.006749,-0.009950
feature_noise_1,0.016400,0.001560,0.012451,0.007977,0.005980,-0.005491,0.011297,-0.001185,-0.015262,0.005606,...,0.026359,-0.011492,0.000642,0.002962,0.002555,0.000747,1.000000,-0.000417,-0.019444,-0.010197
feature_noise_2,-0.009458,0.010229,0.004949,-0.004281,0.002677,0.006643,0.002188,0.011254,0.003920,-0.001240,...,0.014793,-0.006047,-0.012593,0.009060,0.004097,0.015760,-0.000417,1.000000,0.000595,-0.001456
feature_noise_3,0.017404,-0.009505,-0.006545,-0.007114,0.020676,-0.014723,-0.006895,-0.011570,-0.005668,0.005497,...,0.008918,0.001063,-0.028287,0.002392,0.004518,-0.006749,-0.019444,0.000595,1.000000,-0.015924
feature_noise_4,0.011321,0.000669,-0.003603,0.006085,-0.014923,0.024674,-0.014247,0.022639,0.008154,-0.014561,...,0.010143,-0.003969,-0.007067,0.000584,-0.002108,-0.009950,-0.010197,-0.001456,-0.015924,1.000000